// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_resolve
Rcpp::List rcpp_resolve(Rcpp::List& person_data, int int_res_status, std::string initial_date_finalised, int& tw, int& tm);
RcppExport SEXP _migrbc_rcpp_resolve(SEXP person_dataSEXP, SEXP int_res_statusSEXP, SEXP initial_date_finalisedSEXP, SEXP twSEXP, SEXP tmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type person_data(person_dataSEXP);
    Rcpp::traits::input_parameter< int >::type int_res_status(int_res_statusSEXP);
    Rcpp::traits::input_parameter< std::string >::type initial_date_finalised(initial_date_finalisedSEXP);
    Rcpp::traits::input_parameter< int& >::type tw(twSEXP);
    Rcpp::traits::input_parameter< int& >::type tm(tmSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_resolve(person_data, int_res_status, initial_date_finalised, tw, tm));
    return rcpp_result_gen;
END_RCPP
}
// run_rbc_process_core
Rcpp::DataFrame run_rbc_process_core(Rcpp::List& cross_data, Rcpp::List& ini_status_data, int& tw, int& ty);
RcppExport SEXP _migrbc_run_rbc_process_core(SEXP cross_dataSEXP, SEXP ini_status_dataSEXP, SEXP twSEXP, SEXP tySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type cross_data(cross_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type ini_status_data(ini_status_dataSEXP);
    Rcpp::traits::input_parameter< int& >::type tw(twSEXP);
    Rcpp::traits::input_parameter< int& >::type ty(tySEXP);
    rcpp_result_gen = Rcpp::wrap(run_rbc_process_core(cross_data, ini_status_data, tw, ty));
    return rcpp_result_gen;
END_RCPP
}
// run_rbc_process_with_error
Rcpp::DataFrame run_rbc_process_with_error(Rcpp::List& cross_data, Rcpp::List& ini_status_data, StringVector& error_message, int& tw);
RcppExport SEXP _migrbc_run_rbc_process_with_error(SEXP cross_dataSEXP, SEXP ini_status_dataSEXP, SEXP error_messageSEXP, SEXP twSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type cross_data(cross_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type ini_status_data(ini_status_dataSEXP);
    Rcpp::traits::input_parameter< StringVector& >::type error_message(error_messageSEXP);
    Rcpp::traits::input_parameter< int& >::type tw(twSEXP);
    rcpp_result_gen = Rcpp::wrap(run_rbc_process_with_error(cross_data, ini_status_data, error_message, tw));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_migrbc_rcpp_resolve", (DL_FUNC) &_migrbc_rcpp_resolve, 5},
    {"_migrbc_run_rbc_process_core", (DL_FUNC) &_migrbc_run_rbc_process_core, 4},
    {"_migrbc_run_rbc_process_with_error", (DL_FUNC) &_migrbc_run_rbc_process_with_error, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_migrbc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
